MyBlog/MyBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tlion/', include('tlion.urls', namespace='tlion')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    # url(r'^hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', logout),
]

MyBlog/comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_comment, name='article_comment'),

]

MyBlog/tlion/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from django.conf.urls import url
from . import views


app_name = 'tlion'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^article/(?P<pk>[0-9]+)/$', views.article_page, name='article_page'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag'),

    url(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page, name='edit_page'),
    url(r'^modify/action/$', views.modify_action, name='modify_action'),
    url(r'^edit/action/$', views.edit_action, name='edit_action'),
    url(r'^contact/', views.contact, name='contact'),

    url(r'^likes/(?P<article_id>[0-9]+)/$', views.collect_likes, name='likes'),
    url(r'^views/$', views.collect_views, name='views'),
]
urlpatterns += staticfiles_urlpatterns()

MyBlog/tlion/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    modifies_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    STATUS_CHOICES = (
        ('p', 'Published'),
        ('d', 'Drafted')
    )
    title = models.CharField(max_length=70, null=False)
    content = models.TextField()
    head_img = models.ImageField(upload_to='uploads/', blank=True, default='static/img/1.jpg')

    create_time = models.DateTimeField(auto_now_add=True)
    modifies_time = models.DateTimeField(auto_now=True)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
    excerpt = models.CharField(max_length=54, blank=True, null=True)

    views = models.PositiveIntegerField('浏览量', default=0)
    likes = models.PositiveIntegerField('点赞数', default=0)
    comments_num = models.PositiveIntegerField(default=0)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)

    class Meta:
        # Meta 包含一系列选项，这里的 ordering 表示排序，- 号表示逆序。即当从数据库中取出文章时，其是按文章最后一次修改时间逆序排列的。
        ordering = ['-modifies_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tlion:article_page', kwargs={'pk': self.pk})

MyBlog/tlion/forms.py
from django import forms

from .models import Article
from . import models


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        type = (
            ('p', 'publish'),
            ('d', 'draft')
        )
        author = models.User.objects.all().values_list('id', 'username')

        cate = models.Category.objects.all().values_list('id', 'name')

        tags = models.Tag.objects.all().values_list('id', 'name')

        fields = ['title', 'content', 'status', 'author', 'category', 'tags', 'head_img']

        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': "请输入标题",
            }),

            'content': forms.Textarea(attrs={
                'placeholder': '请输入内容...', }),

            'status': forms.Select(choices=type),

            'author': forms.Select(choices=author),

            'cagetory': forms.Select(choices=cate),

            'tag': forms.CheckboxSelectMultiple(choices=tags),
        }

MyBlog/tlion/views.py
import markdown2
from . import models
from . models import Article, Category, Tag
from django.shortcuts import render, get_object_or_404, redirect
from comments.forms import CommentForm
from comments.models import Comment
from .forms import ArticleForm
from django.http import HttpResponse
import os
import datetime


def index(request):

    articles = Article.objects.filter(status='p')
    for article in articles:
        article.content = markdown2.markdown(article.content)
    context = {
        'articles': articles
    }
    return render(request, 'tlion/index.html', context=context)


def article_page(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.content = markdown2.markdown(article.content)
    form = CommentForm()
    comments = Comment.objects.filter(article=article)

    context = {
        'article': article,
        'form': form,
        'comments': comments
    }

    return render(request, 'tlion/article_page.html', context=context)


def edit_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'tlion/edit_page.html', {'article': article})


def edit_action(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            form_data = form.cleaned_data
            # 自定义图片上传

            # 但是在views也保存了一份,我们给他改掉改成我们自己的就行了
            article = form.save(commit=False)

            article.head_img = form_data['head_img']
            excer = article.content[:200] + '...'
            article.excerpt = excer

            article.save()
            form = CommentForm()

            context = {
                'form': form,
                'article': article
            }

            return render(request, 'tlion/article_page.html', context=context)

        else:
            context = {
                       'form': form,
                       }
            return render(request, 'tlion/edit_new_page.html', context=context)
    form = ArticleForm()
    context = {
        'form': form,
    }

    return render(request, 'tlion/edit_new_page.html', context=context)


'''def handle_upload_file(f, request):

    # f这里获取到文件句柄

    base_img_upload_path = 'static/tlion/uploads'
    user_path = "%s/%s" % (base_img_upload_path, request.author.name)

    if not os.path.exists(user_path):
        os.mkdir(user_path)

    with open('%s/%s' % (user_path, f.name), 'wb+') as destinations:
        for chunk in f.chunks():
            destinations.write(chunk)

    return "/static/Uploads/%s/%s" % (request.user.userprofile.id, f.name)'''


def modify_action(request):
    article_id = request.POST.get('article_id')
    article = models.Article.objects.get(pk=article_id)
    article.title = request.POST.get('title')
    content = request.POST.get('content')

    article.status = request.POST.get('select')
    article.content = content
    article.excerpt = content[:200]
    article.save()

    article.content = markdown2.markdown(article.content)

    form = CommentForm()
    comments = Comment.objects.filter(article=article)

    context = {'article': article,
               'form': form,
               'comments': comments,
    }
    return render(request, 'tlion/article_page.html', context=context)


def archives(request, year, month):
    articles = Article.objects.filter(create_time__year=year, create_time__month=month)
    return render(request, 'tlion/index.html', {'articles': articles})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    articles = Article.objects.filter(category=cate)
    return render(request, 'tlion/index.html', {'articles': articles})


def tag(request, pk):
    tag_ = get_object_or_404(Tag, pk=pk)
    articles = Article.objects.filter(tag=tag_)
    return render(request, 'tlion/index.html', {'articles': articles})


def contact(request):
    return render(request, 'tlion/contact.html')


def thumb_up(request):
    return request(request, '')


def collect_likes(request, article_id):
    article = get_object_or_404(Article, pk=article_id)

    liked_article = request.session.get(article_id)

    if article_id != liked_article:
        article.likes += 1
        article.save()
        request.session[article_id] = article_id
        return redirect(article)

    return redirect(article)


def collect_views(request):

    pk = request.get['pk']
    article = Article.objects.filter(pk=2)

    last_view = request.session.get('last_view')  # 获取最后一次浏览本站的时间last_view
    if last_view:
        last_visit_time = datetime.datetime.strptime(last_view[:-7], "%Y-%m-%d %H:%M:%S")
        if datetime.datetime.now() >= last_visit_time + datetime.timedelta(minutes=5):  # 判断如果最后一次访问网站的时间大于5分钟，则浏览量+1
            article.views += 1
            article.save()
    else:
        article.views += 1
        article.save()
    request.session['last_view'] = str(datetime.datetime.now())

MyBlog/tlion/templates/tlion/article_page.html
{% extends 'tlion/base.html' %}
{% load staticfiles %}{% load tlion_tags %}
{% block title %}<title>article page</title>
{% endblock %}
{% block h1 %}<a href="{% url 'tlion:index' %}"><img src="{% static 'tlion/img/back.jpg' %}" height="40" width="40"> </a>{% endblock %}
{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ article.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ article.category }}</a></span>

                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ article.create_time }}">{{ article.create_time }}</time></a></span>

                <span class="post-author"><a href="#">{{ article.author }}</a></span>

                <span class="post-author"><a href="{% url 'tlion:likes' article.pk %}">{{ article.likes }}likes</a></span>

                <span class="post-author"><a href="">{{ article.views }}views</a></span>

                <span class="comments-link"><a href="#comments">{{ article.comments_num }}comments</a></span>
            </div>
            <div class="entry-meta">
                <span class="center"><a href="{% url 'tlion:edit_page' article.id %}">修改文章</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ article.content|safe }}
        </div>
    </article>
    <!--<section class="comment-area">
        <!-- UY BEGIN -->
        <!--<a name="comments" hidden></a>
        <!--<div id="uyan_frame"></div>
        <!--<script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js?uid=2131702"></script>
        <!-- UY END -->
    <!--</section>-->
        <form action="{% url 'comments:article_comment' article.id %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label }}"></label>
                {{ form.name }}
            </div>

            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}"></label>
                {{ form.email }}
            </div>

            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}"></label>
                {{ form.url }}
            </div>

            <div class="col-md-12">
                {{ form.content }}
                <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>发✈表</span></button>
            </div>
        </div>    <!-- row -->
    </form>

    <!--<form id="user_content" method = 'post' enctype="multipart/form-data">
        <textarea cols="40" id="id_content" name="content" rows="10"></textarea>
        <input id=‘put‘ type="submit" value = "提交" />
    </form>

    <!--<form id="user_content" method="post" class="comment-form" enctype="multipart/form-data">
        <div class="row">
            <input hidden value="">
            <div class="col-md-4">
                <input type="text" name="name" placeholder="名字" required>
            </div>
            <div class="col-md-4">
                <input type="email" name="email" placeholder="邮箱" required>
            </div>
            <div class="col-md-4">
                <input type="text" name="url" id="id_content" placeholder="网址" required>
            </div>
            <div class="col-md-12">
                <textarea name="comment" id="id_content" rows="7" placeholder="" required></textarea>
                <button class=""><span>发表</span></button>
            </div>
        </div>    <!-- row -->

    <div class="comment-list">
            <h2><a name="comments">评论列表({{ article.comments_num }}人评论)：</a></h2>
            <ul class="list-unstyled">
                {% build_comment_tree comments %}
                <p>没有过多的评论了？！！</p>
            </ul>
    </div>
{% endblock %}
{% block aside %}
    <section id="text-20" class="block widget">
                                <div class="textwidget"><script async src="{% static 'tlion/js/adsbygoogle.js' %}"></script>
                            <!-- 自适应_右侧栏 -->
                                    <p class="ui red text-center">文章专栏：</p>
                                <script>
                                (adsbygoogle = window.adsbygoogle || []).push({});
                                </script></div>
                            </section>

    <section id="text-15" class="block widget widget_text">
                                <p class="ui red ribbon label">新文章：</p>
                                <div class="textwidget">
                                    {% get_recent_articles as articles %}
                                <ul>
                                    {% for article in articles %}
                                    <li class="recent-comments">
                                        <a href="{{ article.get_absolute_url }}">
                                            <div class="recent-avatar"><img alt='' src='/tlion/static/tlion/img/{{ article.head_img }}' height='32' width='32' /></div>
                                            <div class="recent-body">
                                                <p class="recent-author">{{ article.author }}:</p>
                                                <p class="recent-text">{{ article.title }}</p>
                                            </div>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul></div>
                            </section>

    <section id="text-15" class="block widget widget_category">
                                <p class="ui red ribbon label">文章分类：</p>
                                <div class="textwidget">
                                    {% get_categories as categories %}
                                <ul>
                                    {% for category in categories %}
                                    <li class="recent-comments">
                                        <a href="{% url 'tlion:category' category.id %}">

                                            <P align="center">{{ category.name }}</P>

                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul></div>
                            </section>

    <section id="text-15" class="block widget widget_tags">
                                <p class="ui red ribbon label">文章标签：</p>
                                <div class="textwidget">
                                    {% get_tags as tags %}
                                <ul>
                                    {% for tag in tags %}
                                    <li class="recent-comments">
                                        <a href="{% url 'tlion:tag' tag.id %}">

                                            <p align="center">{{ tag.name }}</p>

                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul></div>
                            </section>

    <section id="views-3" class="block widget widget_archives">
                                <p class="ui red ribbon label">归档：</p>
                                {% archives as dates %}
                                <ul>
                                    {% for date in dates %}
                                <li>
                                    <a href="{% url 'tlion:archives' date.year date.month %}"><p align="center">{{ date.year }}年{{ date.month }}月</p></a>
                                </li>
                                    {% endfor %}
                                </ul>
                            </section>

    <section id="text-8" class="block widget widget_text">
                            <div class="textwidget">
                                <div class="close-side">关闭侧边栏</div>
                                <br>
                            </div>
    </section>
{% endblock %}

MyBlog/tlion/templates/tlion/base.html
{% load tlion_tags %}
{% load paginate_tags %}
<!DOCTYPE html>
<html>
	<head>
		{% block title %}{% endblock %}

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}

	    <!-- css -->
        <link rel="stylesheet" href="{% static 'tlion/css/animations.css'%}">
        <link rel="stylesheet" href="{% static 'tlion/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'tlion/css/style.css' %}">
		<link rel="stylesheet" href="{% static 'tlion/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'tlion/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'tlion/css/custom.css' %}">

	    <!-- js -->
	    <script src="{% static 'tlion/js/jquery-2.1.3.min.js' %}"></script>
	    <script src="{% static 'tlion/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'tlion/js/pace.min.js' %}"></script>
        {% block statics %}{% endblock %}
	</head>
	<body>
        <div>
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							{% block h1 %}{% endblock %}
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right" id="menu-top-menu">
    								<li class="cl-effect-11"><a href="{% url 'tlion:index' %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                                    <li class="cl-effect-11"><a href="{% url 'tlion:contact' %}" data-hover="Contact">Contact</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="More">More</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>

						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>

					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="copyrights">Collect from waper template and so..on..</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
						{% block main %}{% endblock %}
					</main>

					<aside class="col-md-4">
                        {% block aside %}{% endblock %}
				    </aside>
                </div>
			</div>
		</div>

		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
                        <p class="copyright">访问统计量{% get_count %}</p>
                        <p class="copyright">&copy; 2014 ThemeWagon.com -More Templates <a href=" " target="_blank" title="模板之家"></a> - Collect from <a href=" " title="网页模板" target="_blank"></a></p>
					</div>
				</div>
			</div>
		</footer>
		<!-- Mobile Menu -->

		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>
    {% block footer %}{% endblock %}
    </body>
</html>

MyBlog/tlion/templates/tlion/index.html
{% extends 'tlion/base.html' %}
{% block title %}
    {% load staticfiles %}
    {% load tlion_tags %}
    <title>My&Blog</title>
{% endblock %}
{% block statics %}
    <style type='text/css'>

        .is-animate.style1 > div { animation-name: style1; }

        .is-animate > div {
          animation-duration: 1s;
          animation-fill-mode: both;
          animation-iteration-count: infinite;
        }

        .is-animate > div:nth-child(1) { animation-delay: 0.0s }
        .is-animate > div:nth-child(2) { animation-delay: 0.1s }
        .is-animate > div:nth-child(3) { animation-delay: 0.2s }

    </style>
    <link rel="stylesheet" href="{% static 'tlion/css/animations.css'%}">
    <script>
            $(document).ready(function(){
            $('#view_collect').click(function(){

                $.post("{% url 'tlion:views' %}",{
                    id:'{{ article.id }}'
                });
            });
        });
    </script>
{% endblock %}
{% block h1 %}<a href="{% url 'tlion:edit_action' %}">
    <h1>
        new article
    </h1>
</a>{% endblock %}
{% block main %}
    {% load tlion_tags %}
    {% load paginate_tags %}
    {% load hitcount_tags %}
    {% paginate articles 3 %}

    {% for article in articles %}
        <section class="block widget">
            <article class="post block">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ article.get_absolute_url }}" class="" id="view_collect">{{ article.title }}</a>
                    </h1>
                    <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'tlion:category' article.category_id %}">{{ article.category }}</a></span>

                            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ article.create_time }}">{{ article.create_time }}</time></a></span>

                            <span class="post-author"><a href="#">{{ article.author }}</a></span>

                            <span class="post-author"><a href="#">{{ article.views }}浏览</a></span>

                            <span class="post-author"><a href="#">{{ article.likes }}喜欢</a></span>

                            <span class="comments"><a href="#">{{ article.comments_num }}comments</a></span>
                    </div>
                </header>
                <div class="row">
                    <div class="col-lg-4">
                        <a href="{{ article.get_absolute_url }}" class="more-link" id="view_collect"><img src="/tlion/static/tlion/img/{{ article.head_img }}" class="img-rounded" alt="{{ article.title }}"></a>
                    </div>
                    <div class="noteentry-content clearfix note">
                        <p><br><br>{{ article.excerpt }}...</p>
                    </div>
                </div>

                <div class="read-more cl-effect-14">
                    <a href="{{ article.get_absolute_url }}" class="more-link" id="view_collect">Continue readinG<span class="meta-nav">→</span></a>
                </div>
            </article>
        </section>
    {% empty %}
        <div class="no-post"><p>暂时还没有发布的文章！</p>
        </div>
    {% endfor %}
    <section class="widget block col-md-12">
        <div class="pagination">
        <strong>{% include 'tlion/pagination.html' %}</strong>
        </div>
    </section>

{% endblock %}
{% block aside %}
    <section id="text-11" class="block widget widget_text">
                            <div class="textwidget">
                                <div class="ca-container">
                            <div class="ca-head">
                                <div class="ca-head-container">
                                    <img src="{% static 'tlion/img/timg.gif' %}">
                                    <h1><span>Tlion</span>魏冰心BLOG</h1>
                                </div>
                            </div>
                            <div class="ca-body">
                                <p>你能抓到我么？</p>
                                <div class="catch-me">
                                    <div>
                                    <a data-balloon="Rss" data-balloon-pos="up" target="_blank" href="https://www.anotherhome.net/feed"><i class="fa fa-rss">1</i></a>
                                    <a data-balloon="微博" data-balloon-pos="up" target="_blank" href="http://weibo.com/anotherhome" class="external" rel="nofollow"><i class="fa fa-weibo">fe1</i></a>
                                    <a data-balloon="GitHub" data-balloon-pos="up" target="_blank" href="https://github.com/DIYgod" class="external" rel="nofollow"><i class="fa fa-github">1fe</i></a>
                                    </div>
                                    <div>
                                    <a data-balloon="Instagram" data-balloon-pos="up" target="_blank" href="https://www.instagram.com/diygod" style="display:none;" class="external" rel="nofollow"><i class="fa fa-instagram">1fe</i></a>
                                    <a data-balloon="QQ群" data-balloon-pos="up" target="_blank" href="https://diygod.b0.upaiyun.com/qq-g.jpg" class="external" rel="nofollow"><i class="fa fa-qq">1QQ</i></a>
                                    <a data-balloon="微信公众号" data-balloon-pos="up" target="_blank" href="https://diygod.b0.upaiyun.com/gzh.jpg" class="external" rel="nofollow"><i class="fa fa-wechat">zhi</i></a>
                                    <a data-balloon="telegram" data-balloon-pos="up" target="_blank" href="https://telegram.me/prpr233" class="external" rel="nofollow"><i class="fa fa-telegram">zhi</i></a>
                                    <a data-balloon="知乎" data-balloon-pos="up" target="_blank" href="https://www.zhihu.com/people/diygod" class="external" rel="nofollow"><i  class="fa" style="font-weight: 500;">知</i></a>
                                    </div>
                                </div>
                            </div>
                                </div>
                            </div>
                        </section>

    <section id="text-4" class="block widget widget_text">
                        <div class="textwidget">
                                <div class='like-vote'>
                                    <p class='like-title'>Do you like me?</p>
                                    <div class='like-count'>
                                        <p class="fa fa-heart"></p><span>❤likes</span>
                                    </div><br>
                                </div>
                        </div>
		</section>

    <section id="text-20" class="block widget">
                            <div class="textwidget"><script async src="{% static 'tlion/js/adsbygoogle.js' %}"></script>
                        <!-- 自适应_右侧栏 -->
                                <p class="ui red text-center"><span><--文章专栏--></span></p>
                            <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                            </script></div>
                        </section>

    <section id="text-15" class="block widget widget_text">
                            <p class="ui red ribbon label">新文章：</p>
                            <div class="textwidget">
                                {% get_recent_articles as articles %}
							<ul>
                                {% for article in articles %}
								<li class="recent-comments">
									<a href="{{ article.get_absolute_url }}">
                                        <div class="recent-avatar"><img src='/tlion/static/tlion/img/{{ article.head_img }}' height='32' width='32' /></div>
                                        <div class="recent-body">
                                            <p class="recent-author">{{ article.author }}:</p>
                                            <p class="recent-text">{{ article.title }}</p>
                                        </div>
                                    </a>
								</li>
                                {% endfor %}
                            </ul></div>
                        </section>

    <section id="text-15" class="block widget widget_category">
                            <p class="ui red ribbon label">文章分类：</p>
                            <div class="textwidget">
                                {% get_categories as categories %}
							<ul>
                                {% for category in categories %}
								<li class="recent-comments">
									<a href="{% url 'tlion:category' category.id %}">

                                        {{ category.name }}

                                    </a>
								</li>
                                {% endfor %}
                            </ul></div>
                        </section>

    <section id="views-3" class="block widget widget_archives">
                            <p class="ui red ribbon label">归档：</p>
                            {% archives as dates %}
                            <ul>
                                {% for date in dates %}
                            <li>
                                <a href="{% url 'tlion:archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                            </li>
                                {% endfor %}
                            </ul>
                        </section>

    <section id="text-8" class="block widget widget_text">
                            <div class="textwidget">
                                <div class="close-side">关闭侧边栏</div>
                                <br>
                            </div>
                        </section>
{% endblock %}
{% block footer %}
    <a href="#" id="scroll-top" style="display: inline;"><img src="{% static 'tlion/img/up.png' %}"></a>
{% endblock %}