clean_blog-master/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostView.as_view(), name='detail'),
    url(r'^archive/$', views.archives, name='archives_page'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
]

clean_blog-master/cleanblog/urls.py
import xadmin
from django.conf.urls import url, include
from cleanblog.settings import MEDIA_ROOT
from django.views.static import serve
from blog.feed import AllPostRssFeed

xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()

from ckeditor_uploader import urls as ckeditor_uploader_urls

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^ckeditor/', include(ckeditor_uploader_urls)),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^all/rss/$', AllPostRssFeed(), name='rss'),
]

clean_blog-master/comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

clean_blog-master/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    author = models.ForeignKey(User)
    tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(Category)
    # content = models.TextField()
    content = RichTextUploadingField(verbose_name='content', config_name='vul')

    created_time = models.DateTimeField()
    summary = models.CharField(max_length=200)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

clean_blog-master/comments/models.py
from django.db import models


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.content[:20]

clean_blog-master/comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.Form):
    name = forms.CharField(
        label='Name',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'})
    )
    email = forms.EmailField(
        label='Email',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
    )
    content = forms.CharField(
        label='Comment',
        widget=forms.TextInput(attrs={'class': 'form-control',
                                     'placeholder': 'Content',
                                     'row': 3})
    )

clean_blog-master/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Post, Category
from comments.forms import CommentForm

import markdown


def archives(request):
    date_list = Post.objects.dates('created_time', 'month', order='DESC')
    return render(request, 'archives.html', context={'date_list': date_list})


class IndexView(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'post_list'
    paginate_by = 5


class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)


    def get_context_data(self, **kwargs):
        context = super(ArchivesView, self).get_context_data(**kwargs)
        title = '{} 年 {} 月'.format(self.kwargs.get('year'), self.kwargs.get('month'))
        context.update({
            'title': title
        })
        return context


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        title = '{}'.format(get_object_or_404(Category, pk=self.kwargs.get('pk')))
        context.update({
            'title': title
        })
        return context


class PostView(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        # markdown
        post = super(PostView, self).get_object(queryset=None)
        post.content = markdown.markdown(post.content,
                                         extensions=[
                                             'markdown.extensions.extra',
                                             'markdown.extensions.codehilite',
                                             'markdown.extensions.toc',
                                         ])
        return post

    def get_context_data(self, **kwargs):
        # form and comment_list
        context = super(PostView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list,
        })
        return context

clean_blog-master/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect

from blog.models import Post
from .models import Comment
from .forms import CommentForm

def post_comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']
            comment = Comment(name=name, email=email, content=content)
            comment.post = post
            comment.save()
            return redirect(post)
        else:
            comment_list = post.comment_set.all()
            return render(request, 'post.html', context={'post': post,
                                                         'form': form,
                                                         'comment_list':comment_list})

    return redirect(post)

clean_blog-master/templates/archives.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block nav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:index' %}">Home
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">About</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'blog:archives_page' %}">Archives</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'rss' %}">RSS</a>
  </li>
</ul>
{% endblock nav %}

{% block main %}
<!-- Blog Entries Column -->
<div class="col-md-8">

  <h1 class="my-4">Archives</h1>

  <!-- Blog Post -->
  <ul class="list-group">
    {% for date in date_list %}
      <li class="list-group-item ">
          <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month}} 月</a>
      </li>
    {% empty %}
    <li class="list-group-item ">
      Not Available
    </li>
    {% endfor %}
    </ul>

</div>
{% endblock main %}

clean_blog-master/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home</title>

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/blog-home.css' %}" rel="stylesheet">
    <!-- highlight -->
    <style>
        span.highlighted {
            color: red;
        }
    </style>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Clean Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          {% block nav %}
          {% endblock nav%}
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        {% block main %}
        {% endblock main %}

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                <div class="input-group">
                  <input type="search" name="q" class="form-control" placeholder="Search for...">
                  <!--<span class="input-group-btn">-->
                  <button class="btn btn-secondary" type="submit"><span class="ion-ios-search-strong">Go!</span></button>
                  <!--</span>-->
                </div>
              </form>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Category</h5>
            <div class="card-body">
              {% cate_list as c_list %}
                <ul class="list-group">
                  {% for cate in c_list %}
                  <li class="list-group-item ">
                    <a href="{% url 'blog:category' cate.pk %}">{{ cate.name }} <span class="badge label-primary">{{ cate.post_num }}</span></a>
                  </li>
                  {% empty %}
                  not available
                </ul>
              {% endfor %}
            </div>
        </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Clean Blog 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>



  </body>

</html>

clean_blog-master/templates/index.html
{% extends 'base.html' %}

{% block nav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'blog:index' %}">Home
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">About</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:archives_page' %}">Archives</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'rss' %}">RSS</a>
  </li>
</ul>
{% endblock nav %}


{% block main %}
<!-- Blog Entries Column -->
<div class="col-md-8">

  <h1 class="my-4">{% if title %}{{ title }}{% else %}Post List{% endif %}</h1>

  {% if error_msg %}
    <p>{{ error_msg }}</p>
  {% endif %}

  <!-- Blog Post -->
  {% for post in post_list %}
  <div class="card mb-4">
    <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
    <div class="card-body">
      <h2 class="card-title">{{ post.title }}</h2>
      <p class="card-text">{{ post.summary }}</p>
      <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
    </div>
    <div class="card-footer text-muted">
      发布于 {{ post.created_time }} by
      <a href="#">{{ post.author }}</a>
    </div>
  </div>
  {% empty %}
  <div class="card mb-4">
    <div class="card-body">
      <h2 class="card-title">Not Available</h2>
    </div>
  </div>
  {% endfor %}


  <!-- Pagination -->

  {% if is_paginated %}
  <ul class="pagination justify-content-center mb-4">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Older</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">&larr; Older</a>
    </li>
    {% endif %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Newer &rarr;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">Newer &rarr;</a>
    </li>
    {% endif %}
  </ul>
  {% endif %}

</div>
{% endblock main %}

clean_blog-master/templates/post.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block nav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:index' %}">Home
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">About</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:archives_page' %}">Archives</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'rss' %}">RSS</a>
  </li>
</ul>
{% endblock nav %}

{% block main %}

<!-- Post Content Column -->
<div class="col-lg-8">

  <!-- Title -->
  <h1 class="mt-4">{{ post.title }}</h1>

  <!-- Author -->
  <p>{{ post.created_time }} by <a href="#">{{ post.author }}</a></p>

  {% for tag in post.tags.all %}
    <span class="label label-success"> {{ tag.name }} </span>
  {% endfor %}

  <hr>

  <!-- Post Content -->
  {{ post.content|safe }}
  <hr>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Comment</h4>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
          {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.name.id_for_label }}">Name</label>
              {{ form.name }}
              {{ form.name.errors }}
            </div>
            <div class="form-group">
              <label for="{{ form.email.id_for_label }}">Email address</label>
              {{ form.email }}
              {{ form.email.errors }}
            </div>
            <div class="form-group">
              <label for="{{ form.content.id_for_label }}">Comment</label>
              {{ form.content }}
              {{ form.content.errors }}
              <!--<textarea class="form-control" rows="3"></textarea>-->
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Single Comment -->
  <div class="media mb-4">
    <h4 class="mt-0">
      Comments({{ post.comment_set.count }})
      <!--<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">-->
      <!--Add Your Comment-->
      <!--</button>-->
      <a href="#" class="btn btn-primary" role="button" data-toggle="modal" data-target="#myModal">Add Your Comment</a>
    </h4>
  </div>
  {% for comment in comment_list %}
  <div class="media mb-4">
    <img class="d-flex mr-3 rounded-circle" src="{% static 'blog/img/a.jpg' %}" alt="" width="50" height="50">
    <div class="media-body">
      <h5 class="mt-0">{{ comment.name }}</h5>
        {{ comment.content }}
    </div>
  </div>
  {% empty %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">Not Comment!</h5>
    </div>
  </div>
  {% endfor %}



</div>


{% endblock main %}

clean_blog-master/templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
{% block main %}

<!-- Blog Entries Column -->
<div class="col-md-8">
{% if query %}

  <h1 class="my-4">Search Result</h1>
  <!-- Blog Post -->

    {% for res in page.object_list %}
      <div class="card mb-4">
        <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
        <div class="card-body">
          <h2 class="card-title">{% highlight res.object.title with query %}</h2>
          <p class="card-text">{% highlight res.object.content with query max_length 40 %}</p>
          <a href="{{ res.object.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
          Posted on {{ res.object.created_time }} by
          <a href="#">{{ res.object.author }}</a>
        </div>
      </div>
    {% empty %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">Not Available</h2>
        </div>
      </div>
    {% endfor %}




  <!-- Pagination -->

  {% if page.has_previous or page.has_next %}
  <ul class="pagination justify-content-center mb-4">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?q={{ query }}&amp;page={{ page.previous_page_number }}">&larr; Older</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">&larr; Older</a>
    </li>
    {% endif %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?q={{ query }}&amp;page={{ page.next_page_number }}">Newer &rarr;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">Newer &rarr;</a>
    </li>
    {% endif %}
  </ul>
  {% endif %}

{% endif %}
</div>

{% endblock main %}